// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class CloudApiRegistryLogging: CloudApiRegistryStub {
    let inner: any CloudApiRegistryStub
    let logger: Logger

    public init(_ inner: any CloudApiRegistryStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-apiregistry-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudapiregistry"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudApiRegistry"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getMcpServer(
      request: GetMcpServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiRegistryV1.McpServer {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMcpServer",
        action: {
          (r: GetMcpServerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiRegistryV1.McpServer
          in
          return try await self.inner.getMcpServer(request: r, options: o)
        })
    }

    public func listMcpServers(
      request: ListMcpServersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiRegistryV1.ListMcpServersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMcpServers",
        action: {
          (r: ListMcpServersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiRegistryV1.ListMcpServersResponse
          in
          return try await self.inner.listMcpServers(request: r, options: o)
        })
    }

    public func getMcpTool(
      request: GetMcpToolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiRegistryV1.McpTool {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMcpTool",
        action: {
          (r: GetMcpToolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiRegistryV1.McpTool
          in
          return try await self.inner.getMcpTool(request: r, options: o)
        })
    }

    public func listMcpTools(
      request: ListMcpToolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiRegistryV1.ListMcpToolsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMcpTools",
        action: {
          (r: ListMcpToolsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiRegistryV1.ListMcpToolsResponse
          in
          return try await self.inner.listMcpTools(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
